[package]
name = "audio-mirroring"
version = "0.1.3"
authors = ["Maciej Krüger <mkg20001@gmail.com>", "Tom Wagner <tom.a.wagner@protonmail.com>"]
edition = "2024"
rust-version = "1.85.0"
license = "GPL-3.0-only"
description = "Audio Mirroring for Linux"
repository = "https://github.com/mkg20001/audio-mirroring"
readme = "README.md"
keywords = ["pipewire", "gtk", "audio-mirroring", "gui", "utility"]
categories = ["gui", "multimedia"]
default-run = "audio-mirroring"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pipewire = "0.8.0"
adw = { version = "0.6", package = "libadwaita", features = ["v1_4"] }
glib = { version = "0.19", features = ["log"] }
async-channel = "2.2"

log = "0.4.11"

once_cell = "1.19"

libc = "0.2"
natord = "1.0.9"

#[[bin]]
#name = "test_volume"
#path = "src/bin/test_volume.rs"
